### ISSUE TITLE
Childnodes not deleted from index (ElasticSearch)

### ISSUE THREAD

**Issue by mcl-sz** [SDKits/ExamineX#105]
**Describe the bug**
For example, if the "Authors" node contains some child "Author"-nodes and the "Authors" node is deleted, the "Author"-nodes remain in the External- and DeliveryApi-index.

**License ID**
Your ExamineX license Id (found in your license file) if you are running a licensed version.

**To Reproduce**

- Install for example "Clean"-startkit from Paul Seal (https://marketplace.umbraco.com/package/clean). 
- Rebuild the indexes.
- Delete the "Authors" node to the recyclebin.
- Search for "Paul" in the External- or DeliveryApi index.

The node can still be found in the External- and DeliveryApi-index but should be deleted.

**Expected behavior**
The childnodes should be removed from the External- and DeliveryApi-index if the parentnode is trashed.

**Versions**
 - ExamineX version 3.0.3
 - Umbraco version: 13.3.2
 - Examine version: 3.2.0

**Comment by Shazwazza** [comment]
Thanks for the report, this is confirmed - will ship a new release in the next hour or so. Will ping back here when it is shipped.

**Comment by Shazwazza** [comment]
Hi @mcl-sz Version 3.0.4 has been published which should resolve this issue.

**Comment by mcl-sz** [comment]
Hi @Shazwazza , i can confirm this this issue is resolved but unfortunately https://github.com/SDKits/ExamineX/issues/106 is not fixed in this release.

**Comment by Shazwazza** [comment]
@mcl-sz  oh? Ok let me go check but essentially it is the same issue/code that does that. I'll check.

**Comment by mcl-sz** [comment]
The DeliveryApiContentIndex in Umbraco Examine has a separate PerformDeleteFromIndex method, maybe this has something to do with that?
