### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by RachBreeze** [SDKits/ExamineX#111]
On https://examinex.online/azure/forms the code example is `.AddExamineXForUmbracoForms()` this is marked as oboslete and should be `AddExamineXAzureSearchForUmbracoForms()` on `ExamineX.AzureSearch.Umbraco.Forms` v 6.0.7

**Comment by Shazwazza** [comment]
Thanks for reporting :) Yep, this has changed very recently, I will update the docs.

**Comment by Shazwazza** [comment]
Docs should be updated/published in a couple of mins
https://examinex.online/azure/forms
