### ISSUE TITLE
ExamineX for Elasticsearch does not parse Lucene query correctly

### ISSUE THREAD

**Issue by raimondkempees-arc** [SDKits/ExamineX#113]
**Describe the bug**
I'm trying out ExamineX for Elasticsearch and find that the query posted to Elasticsearch is incorrect in the following cases:

Note I'm probably doing something stupid.

When I do this:

```

           if (_examineManager.TryGetIndex(Constants.UmbracoIndexes.ExternalIndexName, out var examineIndex))
        {
            var searcher = examineIndex.Searcher;
            var query = searcher.CreateQuery().Field("content", q);
            
            var results = query.Execute().Select(r => r.AllValues);

            _logger.LogDebug("We have {x} results.", results.Count());
        }
```

The output is:
`"type" : "parse_exception",
    "reason" : "request body is required",
    "stack_trace" : "org.elasticsearch.ElasticsearchParseException: request body is required\n\tat org.elasticsearch.server@8.6.1/`

When I do this:

```

 if (_examineManager.TryGetIndex(Constants.UmbracoIndexes.ExternalIndexName, out var examineIndex))
        {
            var searcher = examineIndex.Searcher;
            var query = searcher.CreateQuery("content", BooleanOperation.And).Field("content", q);
            
            var results = query.Execute().Select(r => r.AllValues);

            _logger.LogDebug("We have {x} results.", results.Count());
        }
```

I get

`"stack_trace" : "org.apache.lucene.queryparser.classic.ParseException: Cannot parse '+x__IndexType:content +':`

When I do a plain

`searcher.Search("test")`

I get back one result.

**License ID**
No license yet

**To Reproduce**
See above.

**Expected behavior**
I expect to get search results back.

**Versions**
 - ExamineX.Elasticsearch.Umbraco version 3.0.6
 - ExamineX.Shared version 6.0.8
 - ExamineX.Shared.Umbraco 6.0.8
 - Umbraco version **13.5.2** on cloud (so using Umbraco.Cloud.Cms 13.0.0 
 - Examine version 3.3.0

**Comment by raimondkempees-arc** [comment]
Hi @Shazwazza,

Thanks for looking into it. 

- The value of 'q' is simple string 'buildings', nothing special about it.
- The elastic version is 8.6.1

.. But I think that it goes wrong before that, as there's indeed an empty query body sent to ES.

Interestingly, when I bootup the container and Umbraco app and do a search I first also get:

```
NullReferenceException: Object reference not set to an instance of an object.
ExamineX.ElasticSearch.ElasticSearchCustomMultiFieldQueryParser..ctor(ElasticSearchFieldReferences fieldReferences, Analyzer analyzer)
ExamineX.ElasticSearch.ElasticSearchQuery.A(ElasticSearchFieldReferences , PerFieldAnalyzerWrapper )
ExamineX.ElasticSearch.ElasticSearchQuery..ctor(IElasticClient client, ILoggerFactory loggerFactory, string category, ElasticSearchFieldReferences fields, PerFieldAnalyzerWrapper perFieldAnalyzer, ILicenseManager licenseManager, BooleanOperation op)
ExamineX.ElasticSearch.ElasticSearchSearcher.CreateQuery(string category, BooleanOperation defaultOperation)
BenefactGroup.Baseline.Controllers.SearchController.Index(CancellationToken cancellationToken) in SearchController.cs
+
            var query = searcher.CreateQuery("content", BooleanOperation.And).Field("content", q);
lambda_method56(Closure , object , object[] )
Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
```

But on the second go, I get the below in the debug screen:

![image](https://github.com/user-attachments/assets/75df9bae-7232-4505-92ef-557c497690f8)

With Elastic saying:

` "reason" : "Failed to parse query [+x__IndexType:content +]",`

Thanks!

Rai

**Comment by raimondkempees-arc** [comment]
Also, I seem to have two versions of ExamineX.Shared, maybe that's the issue?

![image](https://github.com/user-attachments/assets/0583caf1-6326-4e7d-8e2f-5daa07138cd8)

**Comment by raimondkempees-arc** [comment]
Hi @Shazwazza.

Ok, I did something stupid. The var 'q' is actually coming from:

`Request.Query["q"];`

.. but I see now that this is a StringValues object and not a string, so a 

`searcher.CreateQuery("content", BooleanOperation.And).Field("content", q);`

Does not explicitly call a ToString() on q.

The solution for now is to do

var q = Request.Query["q"].FirstOrDefault();

This also resolves the NPE.

**Comment by Shazwazza** [comment]
Hi @raimondkempees-arc thanks a lot for reporting and diving into this. Looks like there's some enhancements we can do under the hood to make this experience better in case non-string, etc... is passed to the query and I'll see about the bootup "Object reference not set to an instance of an object." since that shouldn't happen. One tip, is to make sure that if you want the count of items returned, to use TotalItemCount and not Linq's Count() on the Examine/ExamineX search results. Doing a Count() will re-execute/iterate the searching which is probably not what you want.

**Comment by raimondkempees-arc** [comment]
Hi,

Thanks a million for your quick support. I had indeed changed that method call already to TotalItemCount.

R.

From: Shannon Deminick ***@***.***>
Date: Monday, 18 November 2024 at 18:08
To: SDKits/ExamineX ***@***.***>
Cc: Raimond Kempees ***@***.***>, Mention ***@***.***>
Subject: Re: [SDKits/ExamineX] ExamineX for Elasticsearch does not parse Lucene query correctly (Issue #113)

Hi @raimondkempees-arc<https://github.com/raimondkempees-arc> thanks a lot for reporting and diving into this. Looks like there's some enhancements we can do under the hood to make this experience better in case non-string, etc... is passed to the query and I'll see about the bootup "Object reference not set to an instance of an object." since that shouldn't happen. One tip, is to make sure that if you want the count of items returned, to use TotalItemCount and not Linq's Count() on the Examine/ExamineX search results. Doing a Count() will re-execute/iterate the searching which is probably not what you want.
