### ISSUE TITLE
Umbraco v9 support

### ISSUE THREAD

**Issue by Shazwazza** [SDKits/ExamineX#37]

**Comment by jreurink** [comment]
Is there any indication when an official release of 3.0.0 will be available? I understand you can't give an exact date, but it would help us if we knew if it's months or weeks away, because we're planning a new project.

**Comment by Shazwazza** [comment]
I plan on having this released asap! either today or next week.

**Comment by jreurink** [comment]
Ah, that's great to hear! Thank you for your quick response.

**Comment by Shazwazza** [comment]
This is shipped now 🎉  https://github.com/SDKits/ExamineX/releases/tag/v3.0.0
