### ISSUE TITLE
Umbraco Cold Boot will trigger an index rebuild on primary servers

### ISSUE THREAD

**Issue by Shazwazza** [SDKits/ExamineX#46]
ExamineX ensures that rebuilds never occur with an Umbraco replica server since that server is essentially read-only as far as indexing goes. However, when Umbraco cold boots on the primary server, it forces indexes to be rebuilt. 

In most cases this is unwanted behavior when an index is centrally hosted like ExamineX. 

To replicate, you can delete the ~/App_Data/TEMP/DistCache folder on the primary server which will remove it's last synced ID and force a cold boot on restart.

**Comment by Shazwazza** [comment]
This looks to be a change in Umbraco behavior in 8.15 with this commit PR https://github.com/umbraco/Umbraco-CMS/pull/10182 which now always rebuilds indexes on a cold boot. This is a fix for Umbraco since it wasn't always doing this before but impacts ExamineX behavior.

**Comment by Shazwazza** [comment]
@simonech I've fixed this up. Here's a 1.3.1 pre-release that you can test. You can download the artifacts and update to nuget using the -Source nuget parameter.

https://dev.azure.com/sdkits/ExamineX/_build/results?buildId=217&view=artifacts&pathAsName=false&type=publishedArtifacts

Can you let me know if this resolves your issue?

**Comment by simonech** [comment]
I'm running on Umbraco 8.13.1, not 8.15

**Comment by Shazwazza** [comment]
@simonech I know. This fix is for all versions.

**Comment by simonech** [comment]
@Shazwazza installed and now it does not delete and recreate the indexes at each restart.
Seems to be fixing the problem.
Thx

**Comment by Shazwazza** [comment]
Great thanks for testing 💪 I'll get this shipped today or tomorrow.
