### ISSUE TITLE
Error when indexing content - Indexing cancellation requested

### ISSUE THREAD

**Issue by darrenferguson** [SDKits/ExamineX#50]
I've got the vast majority of my content items indexed - but certain items yield this message in the logs:

{"@t":"2021-11-04T09:00:05.6396284Z","@mt":"Indexing cancellation requested, cannot
proceed","@l":"Debug","SourceContext":"ExamineX.AzureSearch.AzureSearchIndex","ProcessId":12160,"ProcessName":"w3wp","ThreadId":65,"AppDomainId":5,"AppDomainAppId":"LMW3SVC4ROOT","MachineName":"DESKTOP-L77N24O","Log4NetLevel":"DEBUG"}

Please let me know if I'm able to provide more details!

**Comment by Shazwazza** [comment]
Hi Darren,

Do you have any way to replicate this or have other info relating to it? i.e. Does this occur at a similar time to when an appdomain is shutting down? When this occurs is it due to indexing a document based on an editors interaction or based on some sort of automation?

**Comment by darrenferguson** [comment]
Hi Shannon, 

I'm interactively tailing the log file and get the log extract above shortly after each publish in the back office.

I'm guessing it is something to do with the specific doc type. Most content is indexed without issue, but a small minority of document types yield this error, meaning the index is never complete.

I've set logging levels to debug, and I don't have any additional information beyond the above!

Obviously I'm at a bit of a dead end, as ExamineX is proprietary, so any pointers would be great (we are holding off on a go live, pending resolution).

Many Thanks.

**Comment by Shazwazza** [comment]
Hi Darren, 

I'll investigate this further, it does seem a bit odd. Are you using version 2.0.0?

**Comment by Shazwazza** [comment]
Is there any chance that you are ever doing index rebuilds when this exception occurs?

**Comment by Shazwazza** [comment]
Hi Darren,

Here's some information on this log output... This particular log entry will only occur when the background task cancelation token is canceled. This cancelation will only occur: 

* During appdomain shutdown when the IExamineManager is disposed.
* When the index is rebuilt. When this occurs, any current background indexing operations are canceled. Then rebuilding occurs and then the background task is reset. So while re-indexing is occurring and a user tries to save a document to be indexed, this log entry will occur because the rebuilding operation hasn't completed yet.

Do any of those scenarios sound like it might be what is occurring?

**Comment by darrenferguson** [comment]
Hi Shannon,

For the documents that aren't indexing, I've noted another exception that proceeds the message "Indexing cancellation requested, cannot proceed"

`Previous task was faulted with exception System.AggregateException: One or
more errors occurred. ---> System.InvalidOperationException: No Azure field defined with name heroHubCta\r\n   at
ExamineX.AzureSearch.AzureSearchIndex.B.MoveNext()\r\n   at System.Collections.Generic.List`1..ctor(IEnumerable`1
collection)\r\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n   at
ExamineX.AzureSearch.AzureSearchIndex.A(IEnumerable`1 , CancellationToken )\r\n   at
ExamineX.AzureSearch.AzureSearchIndex.d.A(Task )\r\n   at System.Threading.Tasks.Task.Execute()\r\n   --- End of inner
exception stack trace ---\r\n---> (Inner Exception #0) System.InvalidOperationException: No Azure field defined with
name heroHubCta\r\n   at ExamineX.AzureSearch.AzureSearchIndex.B.MoveNext()\r\n   at
System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\r\n   at
System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n   at
ExamineX.AzureSearch.AzureSearchIndex.A(IEnumerable`1 , CancellationToken )\r\n   at
ExamineX.AzureSearch.AzureSearchIndex.d.A(Task )\r\n   at System.Threading.Tasks.Task.Execute()`

heroHubCTA is a document type property that we use:

![image](https://user-images.githubusercontent.com/2164132/141086817-79ae5382-6604-4815-b389-9651b63e0a7b.png)

However you'll note the difference in capitalisation - 'heroHubCta' in the logs vs. 'heroHubCTA' in the doc type definition.

In the Azure Search index, it is created as 'heroHubCTA':

![image](https://user-images.githubusercontent.com/2164132/141086984-48f1b4d7-63fa-4ad4-9795-428ae0708615.png)

It seems that our issue may be that Examine X is modifying the casing of field names somwehere?

Any thoughts would be much appreciated!

**Comment by Shazwazza** [comment]
Awesome thanks for the details, this should help with investigation! I'll report back soon.

**Comment by Shazwazza** [comment]
I've found where this occurs and will push an update shortly into a 2.0.1 version. I'll reply here when it's ready.

**Comment by darrenferguson** [comment]
Thanks Shannon, looking forward to trying it out!

**Comment by darrenferguson** [comment]
Hello Shannon - are you able to give an ETA on the 2.0.1 version please? I'd like to be able to set expectations with our end customer. Many Thanks.

**Comment by Shazwazza** [comment]
Hi @darrenferguson I've just pushed the 2.0.1 patch release. If you can let me know how that goes that would be great

**Comment by Shazwazza** [comment]
See release https://github.com/SDKits/ExamineX/releases/tag/v2.0.1

**Comment by darrenferguson** [comment]
Hi @Shazwazza I just wanted to drop you a note to say that I've seen a variation of this issue using v2.02 and Umbraco 8.17.1

For now I've removed the impacted field from the index - I don't need you to reopen the issue at this stage, this is more to add some details around what I've experienced if you want to troubleshoot it (I'm not going to be working on this project after this week!)

Yesterday - I observed a couple of errors when Umbraco was trying to index content, initially in batches, so I then started to publish items that were missing from the index individually.

Frustratingly the response that was returned from the Azure Search API was a fairly generic "Object reference not set to an instance of an object".

Through some googling, I was able to determine that this is how the Azure Search service responds when you are making a request to index a field that doesn't exist in the index.

To troubleshoot which field was the issue I had to do the following:

- Setup fiddler to monitor the actual indexing request to the Azure API
- Capture the JSON that was being posted to the endpoint (JSON #1)
- In the Azure portal - use the search explorer to get any indexed document (as this gives you JSON with all fields contained) (JSON #2)
- Write a script to compare fields in JSON #1 to JSON #2

As previously, the index contained a field called 'heroHubCTA' and ExamineX was sending 'heroHubCta'.

It seems across the whole 65k content nodes, this field is the only one with an issue!

In my transforming values event - I've had to add:

![image](https://user-images.githubusercontent.com/2164132/146341407-5ccd0670-6350-48c9-b2c1-870e7ea83e55.png)

As you can imagine this is quite hard to debug :)

Again, this is mainly posted in case anyone, is searching for similar issues in future.

One suggestion that I may make at a product level would be to dump the requests made to Azure if a debug/trace mode is enabled. Setting up Fiddler is a little involved....

Another may be the if Azure helpfully responds with 'Object reference not set to an instance of an object' - maybe you could log a hint along the lines of "possible field mismatch" to point people in the right direction.

I hope the above is useful.
