### ISSUE TITLE
Azure.RequestFailedException: Field mapping with target field 'x__Raw_richTextContent' is specified more than once

### ISSUE THREAD

**Issue by darrenferguson** [SDKits/ExamineX#52]
Hi Shannon,

I've closed off the previous issue I had open but am now seeing the exception below in my log files: "Azure.RequestFailedException: Field mapping with target field 'x__Raw_richTextContent' is specified more than once"

I've tried to hook into the Index_CreatingOrUpdatingIndex event and add the following line:

var dupe = e.AzureSearchIndexDefinition.Fields.GroupBy(x => x.Name.ToLower()).Where(g => g.Count() > 1);

But i don't see any duplicate field definitions at this point in the process.

I'm working with v2.0.1 which you released to fix my previous issue.

Please let me know if I can provide any more detail on this.

Many Thanks.

{"@t":"2021-11-16T13:51:42.2833374Z","@mt":"An error occurred processing the index
batch.","@l":"Error","@x":"Azure.RequestFailedException: Field mapping with target field 'x__Raw_richTextContent' is
specified more than once\r\nStatus: 400 (Bad Request)\r\n\r\nContent:\r\n{\"error\":{\"code\":\"\",\"message\":\"Field
mapping with target field 'x__Raw_richTextContent' is specified more than once\"}}\r\n\r\nHeaders:\r\nPragma:
no-cache\r\nContent-Language: REDACTED\r\nclient-request-id:
a1eefa51-6f44-4294-aa88-878bebbedce4\r\nx-ms-client-request-id: a1eefa51-6f44-4294-aa88-878bebbedce4\r\nrequest-id:
a1eefa51-6f44-4294-aa88-878bebbedce4\r\nelapsed-time: 162\r\nOData-Version: 4.0\r\nPreference-Applied:
REDACTED\r\nStrict-Transport-Security: REDACTED\r\nContent-Length: 118\r\nCache-Control: no-cache\r\nContent-Type:
application/json; odata.metadata=minimal\r\nDate: Tue, 16 Nov 2021 13:51:41 GMT\r\nExpires: -1\r\n\r\n   at
Azure.Search.Documents.IndexersRestClient.CreateOrUpdate(String indexerName, SearchIndexer indexer, String ifMatch,
String ifNoneMatch, CancellationToken cancellationToken)\r\n   at
Azure.Search.Documents.Indexes.SearchIndexerClient.CreateOrUpdateIndexer(SearchIndexer indexer, Boolean
onlyIfUnchanged, CancellationToken cancellationToken)\r\n   at ExamineX.AzureSearch.AzureSearchIndex.a(IEnumerable`1
)\r\n   at ExamineX.AzureSearch.AzureSearchIndex.A(IEnumerable`1 , CancellationToken )\r\n   at
ExamineX.AzureSearch.AzureSearchIndex.d.A(Task )","SourceContext":"ExamineX.AzureSearch.AzureSearchIndex","ProcessId":2
4084,"ProcessName":"w3wp","ThreadId":9,"AppDomainId":2,"AppDomainAppId":"LMW3SVC4ROOT","MachineName":"DESKTOP-L77N24O",
"Log4NetLevel":"ERROR"}

**Comment by Shazwazza** [comment]
Looks like it's the "Indexer" update, not the "Index". There's another event `CreatingOrUpdatingIndexer` that you could use. I'll investigate on my end. Could be caused by small case changes while developing and the dictionary values that have been collected don't do a case insensitive comparison.

**Comment by darrenferguson** [comment]
Looks like you are right!

I added an event handler for "CreatingOrUpdatingIndexer".

I put a line of code in like this:

```
var targetDupe = e.AzureSearchIndexerDefinition.FieldMappings
                .GroupBy(x => x.TargetFieldName.ToLower()).Where(g => g.Count() > 1);
```

And when I put a breakpoint in I can see two Field mappings for "__Raw_richtextContent":

SourceFieldName: __Raw_richtextContent
TargetFieldName: x__Raw_richtextContent

SourceFieldName: __Raw_richtextContent
TargetFieldName: x__Raw_richTextContent

In the second occurrence the case of the TargetFieldName has been modified so it contains an uppercase T for "text".

In Azure search the field in the index is created as "x__Raw_richtextContent".

So also in my event I added the following (which is a bit nasty):

```
if (targetDupe.Any())
            {
                var itemToRemove = targetDupe.SelectMany(x => x)
                    .Last();

                e.AzureSearchIndexerDefinition.FieldMappings.Remove(itemToRemove);
            }
```

With this in place all of my content now appears to get indexed!

It only seems to be that one specific field that is causing the issue.

Obviously it'd be great to get a version where I don't have to use the workaround :)

Also - if you are patching stuff - just a reminder I still have the following code in place - to prevent issues with long content values (in my CreatingOrUpdatingIndex event).

```
foreach (var item in e.AzureSearchIndexDefinition.Fields)
            {
                if (item.Name.StartsWith("x__Raw") || item.Name == "content" || item.Name == "content_")
                {
                    item.IsFacetable = false;
                    item.IsFilterable = false;
                    item.IsSortable = false;
                }
            }
```

**Comment by Shazwazza** [comment]
That's good new @darrenferguson . I'll try to get a 2.0.2 release out early next week. Thanks again for the reports and help, much appreciated!

**Comment by Shazwazza** [comment]
[Nuget (19).zip](https://github.com/SDKits/ExamineX/files/7566994/Nuget.19.zip)

Hey @darrenferguson I've attached a zip of the nuget packages for 2.0.2 which I think should resolve all the above issues. Are you able to test before I release?

Many thanks!

**Comment by darrenferguson** [comment]
Hi @Shazwazza - I'll try to test these out on Monday!

**Comment by darrenferguson** [comment]
Hi Shannon,

Installing the updated version from a local nuget repo leads to a YSOD on startup:

```
System.Reflection.ReflectionTypeLoadException: Could not load all types from "ExamineX.AzureSearch.Umbraco.PDF, Version=2.0.2.0, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
. System.IO.FileNotFoundException: Could not load file or assembly 'UmbracoExamine.PDF, Version=0.8.7153.30865, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
```

**Comment by Shazwazza** [comment]
Thanks @darrenferguson , are you using the `ExamineX.AzureSearch.Umbraco.PDF` lib? Sounds like a package resolution issue potentially. If you are using that lib, maybe try re installing https://www.nuget.org/packages/UmbracoCms.UmbracoExamine.PDF ?

**Comment by darrenferguson** [comment]
I think I was having a busy day - I'm not sure how I installed ExamineX.AzureSearch.Umbraco.PDF - but as we aren't using it, I took it out.

I can confirm that my index rebuilds without my workaround in place, now that I have 2.0.2 installed locally.

Would you mind pinging me when you release the "official" nuget package, so I can update here? @Shazwazza 

Thanks!

**Comment by Shazwazza** [comment]
Ace thanks :) I'll push that out shortly then and let you know.

**Comment by Shazwazza** [comment]
@darrenferguson that is pushed now 🎉 Might just have to wait a few minutes for it to become visible.
