### ISSUE TITLE
Umbraco 9, ExamineX Configuration issues

### ISSUE THREAD

**Issue by Zhaph** [SDKits/ExamineX#55]
We're trying to set up pre-production sites for an Umbraco 9 instance using V3.0.0 of ExamineX.

We have the following settings configured in the appsettings.Production.json file (currently on the basis that in lieu of a specific environment definition in `ASPNETCORE_ENVIRONMENT` the platform will use `Production`):

```json
    "ExamineX": {
        "AzureSearchServiceName": "example-search",
        "AzureSearchServiceKey": "...",
        "SiteFriendlyName": "example",
        "EnvironmentType": "ByService",
        "EnvironmentName": "-dev"
    }
```

I would therefore expect ExamineX to connect to `example-search-dev`, however I'm seeing the following errors in App Insights:

> Retry failed after 4 tries. Retry settings can be adjusted in ClientOptions.Retry. (No such host is known. (`example-search.search.windows.net:443`))

Any recommendations around digging into this, or what I've missed for this setup greatly appreciated - it's working as expected on our Umbraco8/ExamineX2 instances.

**Comment by Shazwazza** [comment]
Thanks for the report. I have confirmed this is a bug with the configuration binding. We'll get this fixed asap and get a new version released. I'll update this issue when it's complete.

**Comment by Shazwazza** [comment]
I've just pushed a 3.0.1 version to Nuget. Thanks again.
