### ISSUE TITLE
Environment name is not appended correctly to create full name

### ISSUE THREAD

**Issue by simonech** [SDKits/ExamineX#59]
According to [documentation](https://examinex.online/configuration), and `-` should be placed between search service name and environment name.

I have `ExamineX:AzureSearchServiceName` = `srch-presite`
and `ExamineX:EnvironmentName` = `tst-cze`
so I would expect `srch-presite-tst-cze`

But on my installation, I get the error
`No such host is known. (srch-presitetst-cze.search.windows.net:443)`

The workaround is easy, I can just add a `-` in front of the EnvironmentName, but would be better if the - is added automatically. Would make it cleaner.

**Comment by Shazwazza** [comment]
This was an update made some time ago to ensure maximum flexibility for naming conventions. Some customers' naming conventions do not adhere to always having a prefixed hyphen so the most flexible solution is to just configure the exact suffix that you wish to have which may or may not include the hyphen.

**Comment by simonech** [comment]
Sounds good. But then you must update the docs since they imply the prefixed hyphen.
