### ISSUE TITLE
Updating Langauge variant fields with the lanaguages analyzer

### ISSUE THREAD

**Issue by Matthew-Wise** [SDKits/ExamineX#77]
Hi Shannon,

I am using v4 and trying to follow the docs and example which look to be for V2, `IUmbracoIndexesCreator` is no longer in the umbraco code base so wondering where I need to start my changes from? I also need to add a suggestor but I think I can do that from the CreateOrUpdate index notification.

thanks
Matt

**Comment by Shazwazza** [comment]
Hi, I've updated the docs to reflect how v3/v4 works with examples: https://examinex.online/customization.

For a suggester, you will need to use the [Azure Search APIs directly](https://examinex.online/azure-search-apis) for that. You can also modify the Azure Search index definitions using the CreatingOrUpdatingIndex, CreatingOrUpdatingIndexer events.

**Comment by Matthew-Wise** [comment]
Thanks Shannon I finally got back on to the project!
