### ISSUE TITLE
Custom fieldType Definition for StringCollection that is Filterable

### ISSUE THREAD

**Issue by shgreig-mtm** [SDKits/ExamineX#78]
Hello,

Trying to understand from the docs how to create the field definition of a field to be a StringCollection that is filterable, any advise?

**Comment by Shazwazza** [comment]
Hi, 

Probably the easiest way for now for a filterable string field, would be to handle the CreatingOrUpdatingIndex event and modifying that field there. 

We'll update the APIs to make this easier/clearer though so you would be able to do it without the event and instead by configuring IOptions for that field. 

Also, I've updated the docs to reflect how v3/v4 works with more examples: https://examinex.online/customization.

**Comment by shgreig-mtm** [comment]
Thank you, I'll give it a go tomorrow

**Comment by jrunestone** [comment]
Hi @Shazwazza did you make available another way of setting field attributes without using the event? (And without creating a custom field type).

It's possible to set `filterable=true` on a `StringCollection` via `CreatingOrUpdatingIndex` as of writing.
