### ISSUE TITLE
ExamineX.AzureSearch.Umbraco cannot be installed on an umbraco v12 installation

### ISSUE THREAD

**Issue by netaddicts** [SDKits/ExamineX#86]
Most likely beccause of umbraco core having introduced some breaking changes in v12 

https://docs.umbraco.com/umbraco-cms/fundamentals/setup/upgrading/version-specific#umbraco-12

Especially this one:

A member was added to an interface without a default implementation.
Umbraco.Cms.Infrastructure.Examine.IUmbracoIndex.SupportProtectedContent

**Comment by Shazwazza** [comment]
Hi @netaddicts, yes there was an API breaking change in this Umbraco release. There will be an ExamineX 5.0 released today which brings in a fix for this and support for all latest dependencies and .NET 7.

**Comment by Shazwazza** [comment]
Hi @netaddicts, v5.0.0 has been pushed to Nuget now.
