### ISSUE TITLE
Disable Index modification requests from Subscribers

### ISSUE THREAD

**Issue by Zhaph** [SDKits/ExamineX#91]
Related to #44 we have a number of sites configured in a [load-balanced](https://docs.umbraco.com/umbraco-cms/fundamentals/setup/server-setup/load-balancing/azure-web-apps) set up, with an [explicit publishing server configured](https://docs.umbraco.com/umbraco-cms/fundamentals/setup/server-setup/load-balancing/flexible-advanced#explicit-schedulingpublisher-server), however we're seeing a number of actions from our scaled subscribers where they appear to be attempting to create or update indexes - is it possible to block these servers from even attempting to rebuild indexes, etc.?

Ideally, this would only be performed by the publisher.

**Comment by Shazwazza** [comment]
ExamineX does perform these checks. Specifically, like this: (where ServerRoleAccessor is `IServerRoleAccessor`)

if (ServerRoleAccessor.CurrentServerRole == ServerRole.Subscriber)
{
    return;
}

This check is done within `UmbracoAzureSearchIndex.CreateIndex`, `UmbracoAzureSearchIndex.PerformIndexItems` and `UmbracoAzureSearchIndex.PerformDeleteFromIndex`

So there shouldn't be any requests to Azure Search from any server that is in a subscriber role for index modifications.

Are you able to provide any additional information?

**Comment by Zhaph** [comment]
Thanks @Shazwazza - I was surprised as I thought this was something in place. It forced me to dig deeper into the application - it looks like we've changed the values in our settings to be more inclusive, but didn't update the switch statement that read those values to actually set the server mode correctly.
