### ISSUE TITLE
Range queries are not added to the $filter expression - v5

### ISSUE THREAD

**Issue by chrden** [SDKits/ExamineX#94]
**Packages & versions**
Umbraco - 12.1.1
ExamineX.AzureSearch - 5.0.1
ExamineX.AzureSearch.Umbraco - 5.0.1

**Bug summary**
I am having the same issue as was previously reported for ExamineX v4 with range queries not being added to the `$filter` expression
See same issue for v4: [Range queries are not added to the $filter expression](https://github.com/SDKits/ExamineX/issues/87)

**Specifics**
I previously reported this issue when running an earlier version of Umbraco and ExamineX v4 but the same issue appears to have reappeared in ExamineX v5 (although the [5.0.1 release](https://github.com/SDKits/ExamineX/releases/tag/v5.0.1) suggests the above https://github.com/SDKits/ExamineX/issues/87 fix should be in this version.

**Tests**
Before implementing Examine, the following Lucene query would produce 6 results:
```
+(+x__IndexType:content) +(nodeName:lorem nodeName:ipsum searchableContent:lorem searchableContent:ipsum) +(homeId ge 1157 and homeId le 1157) +(x__NodeTypeAlias:agendasAndMinutesListing x__NodeTypeAlias:communityCentreHub x__NodeTypeAlias:contentPage x__NodeTypeAlias:eventDetail x__NodeTypeAlias:eventListing x__NodeTypeAlias:lostAnimalListing x__NodeTypeAlias:newsDetail x__NodeTypeAlias:newsListing) +hideFromSearch:0 -templateID:0 -x__NodeTypeAlias:searchPage -x__NodeTypeAlias:error404Page -x__NodeTypeAlias:robotsTxt -x__NodeTypeAlias:xmlSitemapPage -x__NodeTypeAlias:sitemapPage
```

With ExamineX v5.0.1, I am receiving the same 6 results (correctly ordered by score) followed by all other Umbraco content documents

When I remove the `homeId` range query, the result is as expected and returns the expected 6 results.

I am using the Examine Fluent API to build my query.

I have also tested with v5.0.0 with the same results.

Let me know if you need any more information

Thanks

**Comment by Shazwazza** [comment]
Hi @chrden,

You might be correct - the latest fix for #87 didn't make it into the 5.0.1 release. A new 5.1 release will be out today shortly which also includes support for Umbraco Forms indexes (if required). 

I'll post here once its shipped.
