### ISSUE TITLE
Allow customization of the internal SearchClientOptions used to create the SearchIndexClient

### ISSUE THREAD

**Issue by Shazwazza** [SDKits/ExamineX#97]
This is so that customers can have more granular control over the underlying SearchIndexClient such as specifying timeout values.

**Comment by ewilkinson-marathon** [comment]
Hello - how can we access & configure the SearchClientOptions to extend timeout values in ExamineX 4.1.9?

**Comment by Shazwazza** [comment]
@ewilkinson-marathon when configuring `AzureSearchIndexOptions` there is a new property called `SearchClientOptions`. I would recommend not messing with these options but if you really want to do this, please ensure that if you do create a new instance of SearchClientOptions that you create it via the AzureSearchIndexOptions.CreateDefaultSearchClientOptions method since these options control how retry policies work for Azure Search and if you don't use AzureSearchIndexOptions.CreateDefaultSearchClientOptions, then the retry policies will be incorrect.
